#!/usr/bin/env python
import rospy
import json_transport
import json

if __name__ == '__main__':
    rospy.init_node('json_talker')
    pub = json_transport.Publisher('json', queue_size=1, latch=True)

    data = json.loads(rospy.get_param("test_data"))
    print("Publishing " + str(data))
    pub.publish(**data)
    rospy.spin()
