#!/usr/bin/env python3
# Software License Agreement (BSD)
#
# \file      test_listener_py
# \authors   Paul Bovbel <pbovbel@locusrobotics.com>
# \copyright Copyright (c) (2018,), Locus Robotics, All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted
# provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions
# and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of
# conditions and the following disclaimer in the documentation and/or other materials provided with
# the distribution.
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to
# endorse or promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
# OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
import json
import json_transport
import rclpy
import sys
import threading
import time

from rclpy.node import Node
from rclpy.qos import DurabilityPolicy
from rclpy.qos import QoSProfile
from rclpy.qos import ReliabilityPolicy


class JsonListener(Node):

    def __init__(self):
        super().__init__('test_listener_py')
        self.declare_parameter('test_data', 'null')
        self.expected = json.loads(self.get_parameter('test_data').value)
        self.received = None
        self.received_event = threading.Event()

        qos = QoSProfile(
            depth=10,
            durability=DurabilityPolicy.TRANSIENT_LOCAL,
            reliability=ReliabilityPolicy.RELIABLE,
        )
        self.subscription = self.create_subscription(
            json_transport.PackedJson,
            'json',
            self._callback,
            qos,
        )

    def _callback(self, msg):
        self.received = msg.data
        self.get_logger().info(f'Received {self.received}')
        self.received_event.set()


if __name__ == '__main__':
    rclpy.init(args=sys.argv)
    node = JsonListener()

    deadline = time.monotonic() + 5.0
    while rclpy.ok() and time.monotonic() < deadline and not node.received_event.is_set():
        rclpy.spin_once(node, timeout_sec=0.1)

    status = 0
    if not node.received_event.is_set():
        node.get_logger().error("Timed out waiting for message on 'json'")
        status = 1
    elif node.received != node.expected:
        node.get_logger().error('Received payload does not match expected payload')
        status = 1

    node.destroy_node()
    rclpy.shutdown()
    sys.exit(status)
